import React, { useEffect, useState } from 'react';
import Card from '../components/Card';
import Loader from '../components/Loader';
import FormField from './../components/FormField';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    console.log(data);
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {
    const fetchPost = async () => {
      setLoading(true);
      try {
        const response = await fetch(
          'https://dalle-arbb.onrender.com/api/v1/post',
          {
            method: 'GET',
            headers: { 'Content-Type': 'application/json' },
          }
        );
        if (response.ok) {
          const result = await response.json();
          setAllPost(result.data.reverse());
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPost();
  }, []);

  return (
    <>
      <section className='max-w-7xl mx-auto'>
        <div>
          <h1 className='font-extrabold text-[#222328] text-[32px]'>
            What Community <span className=' text-rose-500'>Imagine</span>
            <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
              Browse through a collect of imaginative and awesome images
              generated by <span className=' text-rose-500'>AI</span>
            </p>
          </h1>
        </div>
        <div className='mt-16'>
          <FormField />
        </div>
        <div className='mt-10'>
          {loading ? (
            <div className='flex justify-center items-center'>
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className='font-medium text-[#666E75] text-xl mb-3'>
                  Showing Results for{' '}
                  <span className='text-[#222328]'>{searchText}</span>
                </h2>
              )}
              <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                {searchText ? (
                  <RenderCards data={[]} title='No search result found' />
                ) : (
                  <RenderCards data={allPost} title='No posts found' />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </>
  );
};

export default Home;
